# execute the following commands from the "assassignments/04/" folder:
# git clone --depth 1 --branch 'v2.14.2' https://github.com/kubernetes-sigs/kubespray.git
# sudo pip3 install -r ./kubespray/requirements.txt
# ansible-playbook -i ./hosts.yml --become --become-user=root ./kubespray/cluster.yml
all:
  hosts:
    node1:
      ansible_host: 34.75.145.82
      ip: 10.142.0.16
      ansible_ssh_private_key_file: ./ssh_keys/id_rsa
      ansible_user: user # maybe this is not necessary because of the next line?
      ansible_become: True
    node2:
      ansible_host: 35.237.216.255
      ip: 10.142.0.17
      ansible_ssh_private_key_file: ./ssh_keys/id_rsa
      ansible_user: user # maybe this is not necessary because of the next line?
      ansible_become: True
    node3:
      ansible_host: 34.74.18.42
      ip: 10.142.0.18
      ansible_ssh_private_key_file: ./ssh_keys/id_rsa
      ansible_user: user # maybe this is not necessary because of the next line?
      ansible_become: True
  children:
    kube-master:
      hosts:
        node1:
        node2:
        node3:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
